# Generated by Django 5.0.14 on 2026-07-03 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний доступ')),
                ('num_lectures', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість лекцій')),
                ('num_practicals', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість практичних')),
                ('num_labs', models.PositiveSmallIntegerField(default=0, verbose_name='Кількість лабораторних')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='university.discipline', verbose_name='Дисципліна')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='university.group', verbose_name='Група')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='university.semester', verbose_name='Семестр')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Викладач')),
            ],
            options={
                'verbose_name': 'Дозвіл викладачу на журнал',
                'verbose_name_plural': 'Дозволи викладачам на журнали',
                'unique_together': {('teacher', 'discipline', 'group', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(default=1, verbose_name='Порядковий номер')),
                ('topic', models.CharField(blank=True, max_length=255, verbose_name='Тема')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекція'), ('practice', 'Практичне'), ('lab', 'Лабораторне')], default='lecture', max_length=20, verbose_name='Тип заняття')),
                ('max_grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальна оцінка')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='journal.teacherassignment', verbose_name='Дозвіл (журнал)')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
                'ordering': ['lesson_type', 'order_number'],
                'unique_together': {('assignment', 'lesson_type', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Оцінка')),
                ('grade_type', models.CharField(choices=[('current', 'Поточна'), ('module', 'Модульна'), ('exam', 'Екзамен/Залік')], default='current', max_length=20, verbose_name='Тип оцінки')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to=settings.AUTH_USER_MODEL, verbose_name='Виставив')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='university.student', verbose_name='Студент')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.lesson', verbose_name='Заняття')),
            ],
            options={
                'verbose_name': 'Оцінка',
                'verbose_name_plural': 'Оцінки',
                'unique_together': {('student', 'lesson', 'grade_type')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутній'), ('absent', 'Відсутній'), ('late', 'Запізнення'), ('excused', 'Відсутній (поважна причина)')], default='present', max_length=20, verbose_name='Статус')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='university.student', verbose_name='Студент')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='journal.lesson', verbose_name='Заняття')),
            ],
            options={
                'verbose_name': 'Відвідуваність',
                'verbose_name_plural': 'Відвідуваність',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
