# Generated by Django 5.0.14 on 2026-07-03 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва дисципліни')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Код дисципліни')),
            ],
            options={
                'verbose_name': 'Дисципліна',
                'verbose_name_plural': 'Дисципліни',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва факультету')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва семестру')),
                ('academic_year', models.CharField(max_length=20, verbose_name='Навчальний рік')),
                ('is_current', models.BooleanField(default=False, verbose_name='Поточний')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестри',
                'ordering': ['-academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=20, verbose_name='Код спеціальності')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='university.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
                'ordering': ['code'],
                'unique_together': {('faculty', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва групи')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Курс')),
                ('curator', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'dean', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='university.specialty', verbose_name='Спеціальність')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'ordering': ['specialty', 'course', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_book_number', models.CharField(max_length=30, unique=True, verbose_name='№ зачітної книжки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Навчається')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='university.group', verbose_name='Група')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Облік. запис')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
                'ordering': ['group', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
                ('hours', models.PositiveIntegerField(default=0, verbose_name='Кількість годин')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='university.discipline', verbose_name='Дисципліна')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='university.semester', verbose_name='Семестр')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_entries', to='university.specialty', verbose_name='Спеціальність')),
            ],
            options={
                'verbose_name': 'Пункт навчального плану',
                'verbose_name_plural': 'Навчальний план',
                'unique_together': {('specialty', 'discipline', 'course', 'semester')},
            },
        ),
    ]
